
import React, { useState, useEffect } from 'react';
import { db } from '../../services/storageService';
import { ProviderConfig, ProviderType, AgentRole } from '../../types';
import { AgentRegistry } from '../../services/agentRegistry';
import { Youtube, UploadCloud, Save, CheckCircle2, AlertCircle, Loader2 } from 'lucide-react';

const Publishing: React.FC = () => {
  const [provider, setProvider] = useState<ProviderConfig | null>(null);
  const [accessToken, setAccessToken] = useState('');
  const [loading, setLoading] = useState(false);
  const [uploadStatus, setUploadStatus] = useState<'idle' | 'uploading' | 'success' | 'error'>('idle');
  const [statusMsg, setStatusMsg] = useState('');
  const [testFile, setTestFile] = useState<File | null>(null);

  useEffect(() => {
    loadProvider();
  }, []);

  const loadProvider = async () => {
    const providers = await db.getProviders();
    let ytProvider = providers.find(p => p.providerId === 'youtube');
    
    if (!ytProvider) {
      ytProvider = {
        id: 'prov_yt',
        name: 'YouTube Data API',
        type: ProviderType.PUBLISHING,
        providerId: 'youtube',
        isEnabled: false,
        status: 'untested',
        apiKey: '' // using apiKey field to store Access Token for simplicity in this demo
      };
      // Don't save yet, just show form
    }
    
    setProvider(ytProvider);
    setAccessToken(ytProvider.apiKey || '');
  };

  const handleSaveToken = async () => {
    if (!provider) return;
    const updated = { ...provider, apiKey: accessToken, isEnabled: true };
    await db.saveProvider(updated);
    setProvider(updated);
    alert("تم حفظ Access Token بنجاح");
  };

  const handleTestUpload = async () => {
    if (!testFile || !accessToken) return;
    
    setUploadStatus('uploading');
    setStatusMsg('جاري الرفع إلى YouTube (Draft)...');

    const publisherAgent = AgentRegistry[AgentRole.PUBLISHER];
    if (!publisherAgent) return;

    try {
        // We use the Agent's logic to test strictly what the pipeline uses
        const result = await publisherAgent.execute({
            taskId: `pub_test_${Date.now()}`,
            role: AgentRole.PUBLISHER,
            objective: 'Test Upload',
            inputData: {
                videoBlob: testFile,
                title: "AutoVideo Test Upload " + new Date().toLocaleTimeString(),
                description: "Generated by AutoVideo Factory OS - Test Mode",
                accessToken: accessToken
            },
            meta: {
                fromAdminDirector: true,
                timestamp: new Date().toISOString(),
                priority: 'Normal'
            }
        });

        if (result.status === 'SUCCESS') {
            setUploadStatus('success');
            setStatusMsg(`تم الرفع بنجاح! Video ID: ${result.output?.videoId || 'Mock ID'}`);
        } else {
            setUploadStatus('error');
            setStatusMsg(`فشل الرفع: ${result.warnings.join(', ')}`);
        }

    } catch (e: any) {
        setUploadStatus('error');
        setStatusMsg(`خطأ غير متوقع: ${e.message}`);
    }
  };

  return (
    <div className="space-y-8">
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-bold text-white">إعدادات النشر (Publishing)</h2>
          <p className="text-slate-400">ربط قنوات YouTube وتجربة الرفع الآمن (Private)</p>
        </div>
      </div>

      <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
        <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 bg-red-600 rounded-lg flex items-center justify-center text-white">
                <Youtube size={24} />
            </div>
            <div>
                <h3 className="text-lg font-bold text-slate-200">YouTube Data API Integration</h3>
                <p className="text-xs text-slate-500">يتطلب OAuth Access Token بصلاحيات <code>https://www.googleapis.com/auth/youtube.upload</code></p>
            </div>
        </div>

        <div className="space-y-4 max-w-2xl">
            <div>
                <label className="block text-sm text-slate-400 mb-2">Google Access Token</label>
                <div className="flex gap-2">
                    <input 
                        type="password" 
                        value={accessToken}
                        onChange={(e) => setAccessToken(e.target.value)}
                        placeholder="ya29.a0..."
                        className="flex-1 bg-slate-950 border border-slate-700 rounded-lg px-4 py-2 text-slate-200 font-mono text-sm focus:border-red-500 outline-none transition"
                    />
                    <button 
                        onClick={handleSaveToken}
                        className="bg-slate-800 hover:bg-slate-700 text-slate-200 px-4 rounded-lg flex items-center gap-2 transition"
                    >
                        <Save size={18} />
                        <span>حفظ</span>
                    </button>
                </div>
                <p className="text-xs text-slate-600 mt-2">
                    ملاحظة: هذا الرمز مؤقت (1 ساعة). في بيئة الإنتاج الحقيقية، يجب استخدام Refresh Token في الباك إند.
                </p>
            </div>
        </div>
      </div>

      <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
        <h3 className="text-lg font-bold text-slate-200 mb-4 flex items-center gap-2">
            <UploadCloud size={20} className="text-blue-500" />
            <span>تجربة الرفع (Test Upload)</span>
        </h3>

        <div className="border-2 border-dashed border-slate-700 rounded-lg p-8 flex flex-col items-center justify-center bg-slate-950/50">
            <input 
                type="file" 
                accept="video/mp4,video/webm"
                onChange={(e) => setTestFile(e.target.files?.[0] || null)}
                className="hidden" 
                id="file-upload"
            />
            
            {!testFile ? (
                <label htmlFor="file-upload" className="cursor-pointer flex flex-col items-center">
                    <div className="bg-slate-800 p-4 rounded-full mb-3 text-slate-400 hover:text-white transition">
                        <UploadCloud size={32} />
                    </div>
                    <p className="text-slate-400 font-medium">اختر ملف فيديو للتجربة</p>
                    <p className="text-xs text-slate-600 mt-1">MP4 or WebM (Max 5MB for test)</p>
                </label>
            ) : (
                <div className="flex flex-col items-center w-full max-w-md">
                    <div className="flex items-center gap-3 bg-slate-800 px-4 py-3 rounded-lg w-full mb-4">
                        <div className="bg-blue-900/50 p-2 rounded text-blue-400">
                             <UploadCloud size={16} />
                        </div>
                        <span className="text-sm text-slate-200 flex-1 truncate">{testFile.name}</span>
                        <span className="text-xs text-slate-500">{(testFile.size / 1024 / 1024).toFixed(2)} MB</span>
                        <button onClick={() => setTestFile(null)} className="text-slate-500 hover:text-red-400 p-1"><AlertCircle size={16}/></button>
                    </div>

                    <button 
                        onClick={handleTestUpload}
                        disabled={uploadStatus === 'uploading'}
                        className="bg-red-600 hover:bg-red-500 text-white w-full py-2 rounded-lg font-medium transition disabled:opacity-50 flex justify-center items-center gap-2"
                    >
                        {uploadStatus === 'uploading' ? <Loader2 className="animate-spin" size={18} /> : <Youtube size={18} />}
                        <span>رفع إلى YouTube (Private)</span>
                    </button>
                </div>
            )}

            {uploadStatus !== 'idle' && (
                <div className={`mt-6 p-4 rounded-lg w-full max-w-md border flex items-start gap-3 ${
                    uploadStatus === 'success' ? 'bg-green-900/20 border-green-900/50 text-green-400' :
                    uploadStatus === 'error' ? 'bg-red-900/20 border-red-900/50 text-red-400' :
                    'bg-blue-900/20 border-blue-900/50 text-blue-400'
                }`}>
                    {uploadStatus === 'success' ? <CheckCircle2 className="shrink-0" /> : 
                     uploadStatus === 'error' ? <AlertCircle className="shrink-0" /> : 
                     <Loader2 className="animate-spin shrink-0" />}
                    <div>
                        <p className="font-bold text-sm">
                            {uploadStatus === 'success' ? 'نجاح' : uploadStatus === 'error' ? 'خطأ' : 'جاري المعالجة'}
                        </p>
                        <p className="text-xs mt-1 opacity-90 break-all">{statusMsg}</p>
                    </div>
                </div>
            )}
        </div>
      </div>
    </div>
  );
};

export default Publishing;